stages:
  - test
  

coverage:
  stage: test
  image: ruby:2.5.8
  script:
    - apt update
    - apt install nodejs
    - gem install bundler
    # - gem install execjs
    - bundle install
    - bundle exec rspec
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/coverage.xml
  tags:
    - test-runner