stages:
  - test
  

coverage:
  stage: test
  image: ruby:2.5.8
  script:
    - apt update
    - apt install -y nodejs
    - gem install bundler
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws configure set aws_access_key_id ${DEFAULT_ACCESS_KEY} 
    - aws configure set aws_secret_access_key ${DEFAULT_SECRET_KEY}
    - aws configure set default.region ap-southeast-1
    # - gem install execjs
    - bundle install
    - bundle exec rspec
    - aws s3 cp ./coverage/coverage.svg s3://test-coverage-trial/
    - aws s3 cp ./coverage/index.html s3://test-coverage-trial/
  # artifacts:
  #   reports:
  #     coverage_report:
  #       coverage_format: cobertura
  #       path: coverage/coverage.xml
  coverage: '/LOC \((\d+\.\d+%)\) covered/'
  tags:
    - test-runner