# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fe217dab32624e488465248b3a0d306d8378ff20b3d71cab2f59a4780e33523f0d34bc456c68234f0e23492aac1c6b40e5486f1adbbb748b4e824f6dbb700a88

test:
  secret_key_base: 04bdd9778a2e933123f4585b82f459b9e4cf8e6b0239b5ee9f425b85c6cd3128b9ff0b4ad171291da71a0127f56f8416e03ecaa245070def2d7939e675c379a0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
