name: Ruby

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    container: ruby:2.5.8
    steps:
      # - name: Default user
      #   run: whoami
      - uses: actions/checkout@v3
      # - name: Set up Ruby
      # - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      #   with:
      #     ruby-version: '2.5.8'
      - name: Update apt
        run: apt update
      - name: Install nodejs
        run: apt install -y nodejs
      - name: Update bundle
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      # - name: lcov
      #   run: bundle add simplecov-lcov
      - name: Run tests
        run: rspec
      - name: list directory
        run: pwd
      - uses: romeovs/lcov-reporter-action@v0.2.19
        with:
          lcov-file: ./coverage/lcov/gather.lcov
          github-token: ${{ secrets.TEST }}
