name: Ruby

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  test:
    runs-on: self-hosted
    container: ruby:2.5.8
    steps:
      # - name: Default user
      #   run: whoami
      # - uses: actions/checkout@v3
      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      #   with:
      #     ruby-version: '2.5.8'
      - name: Update apt
        run: apt update
      - name: Install nodejs
        run: apt install nodejs
      - name: Update bundle
        run: gem install bundler
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
